### ISSUE TITLE
Integration stopped working?

### ISSUE THREAD

**Issue by dannymertens** [rt400/ReversoTTS-HA#10]
Hi,

I used this integration multiple times a day, but a couple HA versions ago I got this message in my log:

Logger: homeassistant.components.tts
Source: components/tts/__init__.py:641
Integration: Text-to-Speech (TTS) (documentation, issues)
First occurred: 10:00:51 (1 occurrences)
Last logged: 10:00:51

Error on load tts: 1e013003d0b3209c605b88e478279ccc5fc75edd_sofie-belgian-dutch_-_reversotts not in cache!

Everything still worked fine so just a little annoying, but as of today everything completely stopped working, because a lot of family automation's, processes are heavily related to this, I now had to disable the reverso option and moved everything to the TTS cloud service of Nabu Casa this works but we are missing the option of a Belgium voice so hopefully you can have a look and find a fix for this so I can use this very missed integration again?

The strange thing is now even after removing the integration from HACS, and updating all my automation's, scripts, in HA and node-RED, I still got this message in my log any idea how to fix this for time being till when you hopefully find a fix for the Reverso integration to work again?

Thanks!

Versie | core-2021.5.5
-- | --
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Virtuele omgeving | false
Python-versie | 3.8.9
Besturingssysteem | Linux
Versie van het besturingssysteem | 5.9.16
CPU-architectuur | aarch64
Tijdzone | Europe/Brussels

**Comment by marek2k** [comment]
Same problem here. Integration stopped to working after upgrade HA to core-2021.5.5

**Comment by rt400** [comment]
i have made some change that fix it. please update from hacs or manually

**Comment by marek2k** [comment]
> i have made some change that fix it. please update from hacs or manually

It's working again. Thank you very much.

**Comment by rt400** [comment]
Glad it worked out for you.
I close this issue.

**Comment by dannymertens** [comment]
Works great again, thanks!!!

**Comment by leranp** [comment]
The new version was fix the problem, but there is another issue, with the ","
All of my TTS sentences are with  ","  

This is the log:
`Failed to cast media https://XXX.duckdns.org/api/tts_proxy/d9be93a6cb7b906b8239990915055cd933db5d7e_he-il-asaf-hebrew_-_reversotts.mp3 from external_url (https://XXX.duckdns.org). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address`

**Comment by leranp** [comment]
Working for me after the update , thanks

**Comment by leranp** [comment]
it look like there is a problem with the chart "**,**"
when trying to play Hebrew sentence with "**,**" in it
this is the log file:
```
Failed to cast media https://XXX.duckdns.org/api/tts_proxy/8b0822f83fdf95cf500a541af61e81831179912c_he-il-asaf-hebrew_-_reversotts.mp3 from external_url (https://XXX.duckdns.org). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
```

**Comment by rt400** [comment]
@leranp Have you tried a local network address instead of an external network address?

**Comment by leranp** [comment]
> @leranp Have you tried a local network address instead of an external network address?

In my configuration i have 2 address, the local and the external
Tell me what to do and i will try

**Comment by leranp** [comment]
@rt400 tried to add local and external ip to base_url in the TSS configuration , but no luck

**Comment by leranp** [comment]
https://github.com/home-assistant/core/issues/48331

Remove the internal address is HA was fixed the problem, look like this is not related to this addon.

**Comment by rt400** [comment]
i think this is belong to DuckDNS. for me it's work with "," and i have a true web url.
