### ISSUE TITLE
Home Assistant 2021.5.5 - no module named pyttsreverso

### ISSUE THREAD

**Issue by marcinprzybysz86** [rt400/ReversoTTS-HA#11]
Hi,
it was working fine for a month till today:

Platform error: tts
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 853, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 493, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/reversotts/tts.py", line 3, in <module>
    from pyttsreverso import pyttsreverso
ModuleNotFoundError: No module named 'pyttsreverso'

Debug info. What can be done to make it work again?

Wersja | core-2021.5.5
-- | --
Typ instalacji | Home Assistant Supervised
Wersja deweloperska | false
Supervisor | true
Docker | true
Środowisko wirtualne | false
Wersja Pythona | 3.8.9
Rodzina systemu operacyjnego | Linux
Wersja systemu operacyjnego | 4.19.0-13-amd64
Architektura procesora | x86_64
Strefa czasowa | Europe/Warsaw

System operacyjny hosta | Debian GNU/Linux 10 (buster)
-- | --
Kanał aktualizacji | stable
Wersja Supervisora | supervisor-2021.04.3
Wersja Dockera | 20.10.2
Pojemność dysku | 12.7 GB
Pojemność użyta | 6.2 GB
Zdrowy | true
Wspierany | true
API Supervisora | ok
Wersja API | ok
Zainstalowane dodatki | Samba share (9.3.0), File editor (5.2.0), ESPHome (1.17.1), ZeroTier One (0.10.4), Check Home Assistant configuration (3.7.0), Node-RED (9.0.1)

**Comment by fyford** [comment]
I have the same issue, but noticed that my HACS is showing issues in the config. I can remove it and reinstall and re-connect to GITHUB but then need to reboot to enable the Reverso which then breaks HACS again and I get the same PYTTSREVERSO error you mentioned again. I might be wrong but I think this PY library is handled by HACS (in my case) which looks like what is causing this error. For now I am stuck in this loop and have not found a way to get HACS stable.

![image](https://user-images.githubusercontent.com/52793862/119846402-0171b100-bf02-11eb-9eee-df7f3b59d98b.png)

**Comment by fyford** [comment]
Ah, I managed to fix that by removing all YAML entries for HACS, but the issue persists so I'd say it is a Reverso bug
 - Specifically from the HACS team regarding this:
 - "They are publishing stuff not reflected in the repo (and you should NOT use that at all!),"
 
It seems the HACS guys have picked up on this as well.

**Comment by rt400** [comment]
Which platform ? Docker ? or HASS.IO ?
In docker you can enter to the command line console and run:
```
pip uninstall pyttsreverso
pip install pyttsreverso
```
And make restart to the container .
Let me know if this fix it..

**Comment by rt400** [comment]
Another thing, have you tried updating directly from my GITHUB?

**Comment by fyford** [comment]
I am on HASS.IO so I guess that's a no go for me? I just uninstalled it via HACS, will see if a couple of reboots fixes it... if not I will try to install from GITHUB

**Comment by fyford** [comment]
I did re-installs from both GITHUB manually (after clearing all directories in custom components and generating a new REVERSOTTS directory) and HACS. I still get this error:
Platform error tts.reversotts - No module named 'pyttsreverso'

**Comment by fyford** [comment]
I managed to get the error to go away by downloading the module from here:
https://pypi.org/project/pyttsreverso/#files
and copying it into my reversotts folder under custom_components. It all works now.

**Comment by rt400** [comment]
This is really weird, I do not know if it's a limit of HASS.IO because in DOCKER it works normally.
This should automatically pull the files out of PYPI.
I will try to set up a HASS.IO workspace and check it out and update.

**Comment by marcinprzybysz86** [comment]
> I managed to get the error to go away by downloading the module from here:
> https://pypi.org/project/pyttsreverso/#files
> and copying it into my reversotts folder under custom_components. It all works now.

Did you extract the content of the .tgz file or not? 
I've put those 2 files in reversoTTS folder, still no luck :/

**Comment by marcinprzybysz86** [comment]
> This is really weird, I do not know if it's a limit of HASS.IO because in DOCKER it works normally.
> This should automatically pull the files out of PYPI.
> I will try to set up a HASS.IO workspace and check it out and update.

I'm on debian with supervisor, using docker - same problem as fyford's..

**Comment by fyford** [comment]
Hi Marcin,

I just placed the pyttsreverso file in the directory and it started to work. Prior to this I tried out a few others, I've now stuck them in variables so I can switch whenever one stops working. Google seems to work again, stopped working waay back for me so I then switched to Reverso.... 

![image](https://user-images.githubusercontent.com/52793862/121156152-5d143680-c840-11eb-9445-5e6f1dac401d.png)

**Comment by rt400** [comment]
to all that have the problem and didn't use with HACS, need to check if pyttsreverso is on 0.4v.

**Comment by rt400** [comment]
> > This is really weird, I do not know if it's a limit of HASS.IO because in DOCKER it works normally.
> > This should automatically pull the files out of PYPI.
> > I will try to set up a HASS.IO workspace and check it out and update.
> 
> I'm on debian with supervisor, using docker - same problem as fyford's..

why use supervisor on docker ?

**Comment by iron-LAN** [comment]
What did the trick for me was to delete everything from reverso including the yaml entry. Then reinstall it in HACS. Reboot and paste back the yaml entry and reboot once more to load reverso back.

**Comment by rt400** [comment]
the problem still exist ?

**Comment by rt400** [comment]
well guess no, so I close this issue.
