### ISSUE TITLE
Multiple TTS entities

### ISSUE THREAD

**Issue by davidrustingha** [rt400/ReversoTTS-HA#3]
Would it be possible to add the ability to add multiple TTS entries into Hass? For example: I would be able to use 2 diffrent voices or 2 diffrent pitch settings on the same voice.

**Comment by chivagio** [comment]
@davidrustingha you can specify the language in the service call like this : 
entity_id: _MEDIA_PLAYER_
message: _TEXT_TO_SAY_
language: _LANGUAGE_

Where _LANGUAGE_ is one from the list of available languages.

**Comment by iron-LAN** [comment]
Thats awesome. Had not tried that yet, thanks!
