### ISSUE TITLE
Problem with long speech strings

### ISSUE THREAD

**Issue by mobisat** [rt400/ReversoTTS-HA#5]
This code works fine
`  - service: sonos.snapshot
    data: {}
    entity_id: group.sonos
  - data:
      cache: false
      entity_id: group.sonos
      message: Turning off the air freshener
    service: tts.reversotts_say
  - delay: 00:00:02
  - service: sonos.restore
    data: {}
    entity_id: group.sonos`

This code stops at system, very strange, sometimes says as far as system, othertimes just as far as sys

`  - service: sonos.snapshot
    data: {}
    entity_id: group.sonos
  - data:
      cache: false
      entity_id: group.sonos
      message: The automatic heating control system has been selected
    service: tts.reversotts_say
  - data: {}
    entity_id: climate.living_room
    service: climate.turn_on
  - delay: 00:00:02
  - service: sonos.restore
    data: {}
    entity_id: group.sonos`

**Comment by rt400** [comment]
@mobisat what the error you got ?

**Comment by mobisat** [comment]
No error, the TTS doesn't speak the whole phrase. Instead of saying:
"The automatic heating control system has been selected"
is only says
"The automatic heating control system" or "The automatic heating control sys"
and then stops every time. Is there a limit to the number of letters or works that can be used?

**Comment by rt400** [comment]
@mobisat i will check it . maybe there is a limit...

**Comment by mobisat** [comment]
Apart from that it works perfectly for me 👍

**Comment by rt400** [comment]
@mobisat can you share your config ?
i try in hebrew with a long sentence and it works ...

**Comment by rt400** [comment]
@mobisat I tried with a long sentence and it works perfect , so may be your config are wrong. can you share your config ?

**Comment by mobisat** [comment]
I shared the code in the first post (extract from the automations.yaml file), is there anything specific that you want me to post?

**Comment by rt400** [comment]
@mobisat the tts config in HA

**Comment by mobisat** [comment]
In configuration.yaml

# Text to speech
tts:
  - platform: reversotts
    language: "Lucy-British"
    pitch: "100"
    bitrate: "128k"

**Comment by rt400** [comment]
@mobisat i try it on my HA and its work great... i think that the problem is in your system and i can't help you with that. sorry
