### ISSUE TITLE
Long text problem 

### ISSUE THREAD

**Issue by szamq** [rt400/ReversoTTS-HA#7]
I have default configuration. It seems like reverso tts is limited to some number of characters. Is there any way to hack this? For example I'm unable to say random joke like the one below (stops after words "stops in front" )

A lorry driver is driving 200 penguins to London Zoo when his lorry breaks down on the motorway. The driver gets out of the cab and is looking at the engine when a second lorry driver stops in front of him and asks if he needs help. The penguins' driver explains that he is taking the penguins to the zoo and asks if the other man would
take the penguins there. He agrees.
Some hours later, the 2nd lorry driver drives past the first one, who is still waiting on the motorway. The penguins are still on the lorry, and look happy.

**Comment by rt400** [comment]
@szamq Well I do not know if there is a character limit, and even if there is it makes sense.
Text conversion is intended to convert sentences rather than whole text.
The way this system works is only for the purpose of converting a sentence (alert, message) into speech and nothing more.
