### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by athulahk** [rt400/ReversoTTS-HA#8]
I've coped all files to \custom_components\reversotts folder. Added below entry to config file.
```
tts:
  - platform: reversotts
```

Then I tried to validate it using Home assistance configuration validation button and it gives me below error

Platform error tts.reversotts - No module named 'pyttsreverso'

**Comment by rt400** [comment]
Please add more info to help us to fix the problem

**Comment by rt400** [comment]
did you try to restart HA after add this custom components without configuration validation?

**Comment by cureheaded** [comment]
hello everybody, any updates on this?
Got this error too. Installed correctlu on H A 2021.04 sth 
rebooted without validation

**Comment by rt400** [comment]
which platform you have ?

**Comment by cureheaded** [comment]
hi rt400,
Ubuntu 20 sth.
Anyways. This somewhat strange error got me on the wrong foot. I tried different scripts with different data (structures) and got it working.
In my case it needed the language in the script too, even if it was defined in the configuration.yaml.
Hope this helps others too!
